### ISSUE TITLE
14.2. Crateni Crates.io-ga nashr qilish

### ISSUE THREAD

**Issue by orzklv** [rust-lang-uz/book#10]
**Asosiy bo'lim:** #8 

**Production:** https://book.rust-lang.uz/ch14-02-publishing-to-crates-io.html
**Manba:** https://github.com/rust-lang-uz/i10n/blob/main/rustbook-uz/src/ch14-02-publishing-to-crates-io.md

**Comment by ismoilovdevml** [comment]
all done translation finished
