### ISSUE TITLE
14. Cargo va Crates.io haqida ko'proq

### ISSUE THREAD

**Issue by orzklv** [rust-lang-uz/book#8]
**O'z ichiga oladigan bo'limlar:**

- [x] #9 
- [x] #10 
- [x] #11 
- [x] #12 
- [x] #13 

**Production:** https://book.rust-lang.uz/ch14-00-more-about-cargo.html
**Manba:** https://github.com/rust-lang-uz/i10n/blob/main/rustbook-uz/src/ch14-00-more-about-cargo.md

**Comment by ismoilovdevml** [comment]
all done translation finished

**Comment by ismoilovdevml** [comment]
all done translation finished
