### ISSUE TITLE
14.1. Reliz profillari bilan buildarni customizatsiya qilish

### ISSUE THREAD

**Issue by orzklv** [rust-lang-uz/book#9]
**Asosiy bo'lim:** #8 

**Production:** https://book.rust-lang.uz/ch14-01-release-profiles.html
**Manba:** https://github.com/rust-lang-uz/i10n/blob/main/rustbook-uz/src/ch14-01-release-profiles.md

**Comment by ismoilovdevml** [comment]
all done translation finished
